# Generated by Django 3.1.4 on 2021-03-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0003_auto_20210317_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image7',
        ),
    ]
