# Generated by Django 3.1.4 on 2021-03-22 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0009_auto_20210320_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 22, 12, 5, 12, 736011)),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
