# Generated by Django 3.1.4 on 2021-03-23 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0011_auto_20210323_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 23, 12, 57, 29, 954971)),
        ),
    ]
